from ..componentregistry import ComponentRegistry

@ComponentRegistry.register("BinaryTree")
def BinaryTree(content, session, headers, pageObj):
    '''
    {
     "type": "BinaryTree",
     "mode": "edit",
     "content": {
          "version": "3.0",
          "caption": "Example of an Input Binary Tree",
          "svg_string": "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?>\n<!DOCTYPE svg PUBLIC \"-//W3C//DTD SVG 1.1//EN\"\n \"http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd\">\n<!-- Generated by graphviz version 2.40.1 (20161225.0304)\n -->\n<!-- Title: %0 Pages: 1 -->\n<svg width=\"178pt\" height=\"170pt\"\n viewBox=\"0.00 0.00 178.00 170.00\" xmlns=\"http://www.w3.org/2000/svg\" xmlns:xlink=\"http://www.w3.org/1999/xlink\">\n<g id=\"graph0\" class=\"graph\" transform=\"scale(1 1) rotate(0) translate(4 166)\">\n<title>%0</title>\n<!-- node_1 -->\n<g id=\"node_1\" class=\"node\">\n<title>node_1</title>\n<path fill=\"#ffd166\" stroke=\"#000000\" stroke-width=\".5\" d=\"M79.6667,-132.5C79.6667,-132.5 89.3333,-132.5 89.3333,-132.5 94.1667,-132.5 99,-137.3333 99,-142.1667 99,-142.1667 99,-151.8333 99,-151.8333 99,-156.6667 94.1667,-161.5 89.3333,-161.5 89.3333,-161.5 79.6667,-161.5 79.6667,-161.5 74.8333,-161.5 70,-156.6667 70,-151.8333 70,-151.8333 70,-142.1667 70,-142.1667 70,-137.3333 74.8333,-132.5 79.6667,-132.5\"/>\n<text text-anchor=\"middle\" x=\"84.2992\" y=\"-142.2\" font-family=\"Courier,monospace\" font-size=\"16.00\" fill=\"#000000\">5</text>\n</g>\n<!-- node_1606797108896 -->\n<g id=\"node_1606797108896\" class=\"node\">\n<title>node_1606797108896</title>\n<path fill=\"#ffd166\" stroke=\"#000000\" stroke-width=\".5\" d=\"M56.6667,-66.5C56.6667,-66.5 66.3333,-66.5 66.3333,-66.5 71.1667,-66.5 76,-71.3333 76,-76.1667 76,-76.1667 76,-85.8333 76,-85.8333 76,-90.6667 71.1667,-95.5 66.3333,-95.5 66.3333,-95.5 56.6667,-95.5 56.6667,-95.5 51.8333,-95.5 47,-90.6667 47,-85.8333 47,-85.8333 47,-76.1667 47,-76.1667 47,-71.3333 51.8333,-66.5 56.6667,-66.5\"/>\n<text text-anchor=\"middle\" x=\"61.2992\" y=\"-76.2\" font-family=\"Courier,monospace\" font-size=\"16.00\" fill=\"#000000\">0</text>\n</g>\n<!-- node_1&#45;&gt;node_1606797108896 -->\n<g id=\"edge1\" class=\"edge\">\n<title>node_1&#45;&gt;node_1606797108896</title>\n<path fill=\"none\" stroke=\"#000000\" d=\"M79.3956,-132.3525C76.4178,-123.8077 72.6013,-112.8558 69.2582,-103.2626\"/>\n<polygon fill=\"#404040\" stroke=\"#000000\" points=\"71.8669,-102.2396 66.5902,-95.6066 66.5788,-104.0825 71.8669,-102.2396\"/>\n</g>\n<!-- node_1606797070857 -->\n<g id=\"node_1606797070857\" class=\"node\">\n<title>node_1606797070857</title>\n<path fill=\"#ffd166\" stroke=\"#000000\" stroke-width=\".5\" d=\"M103.6667,-66.5C103.6667,-66.5 113.3333,-66.5 113.3333,-66.5 118.1667,-66.5 123,-71.3333 123,-76.1667 123,-76.1667 123,-85.8333 123,-85.8333 123,-90.6667 118.1667,-95.5 113.3333,-95.5 113.3333,-95.5 103.6667,-95.5 103.6667,-95.5 98.8333,-95.5 94,-90.6667 94,-85.8333 94,-85.8333 94,-76.1667 94,-76.1667 94,-71.3333 98.8333,-66.5 103.6667,-66.5\"/>\n<text text-anchor=\"middle\" x=\"108.2992\" y=\"-76.2\" font-family=\"Courier,monospace\" font-size=\"16.00\" fill=\"#000000\">1</text>\n</g>\n<!-- node_1&#45;&gt;node_1606797070857 -->\n<g id=\"edge2\" class=\"edge\">\n<title>node_1&#45;&gt;node_1606797070857</title>\n<path fill=\"none\" stroke=\"#000000\" d=\"M89.8264,-132.3525C92.9336,-123.8077 96.9161,-112.8558 100.4045,-103.2626\"/>\n<polygon fill=\"#404040\" stroke=\"#000000\" points=\"103.0859,-104.0819 103.1885,-95.6066 97.8231,-102.168 103.0859,-104.0819\"/>\n</g>\n<!-- node_1606797087591 -->\n<g id=\"node_1606797087591\" class=\"node\">\n<title>node_1606797087591</title>\n<path fill=\"#ffd166\" stroke=\"#000000\" stroke-width=\".5\" d=\"M9.6667,-.5C9.6667,-.5 19.3333,-.5 19.3333,-.5 24.1667,-.5 29,-5.3333 29,-10.1667 29,-10.1667 29,-19.8333 29,-19.8333 29,-24.6667 24.1667,-29.5 19.3333,-29.5 19.3333,-29.5 9.6667,-29.5 9.6667,-29.5 4.8333,-29.5 0,-24.6667 0,-19.8333 0,-19.8333 0,-10.1667 0,-10.1667 0,-5.3333 4.8333,-.5 9.6667,-.5\"/>\n<text text-anchor=\"middle\" x=\"14.2992\" y=\"-10.2\" font-family=\"Courier,monospace\" font-size=\"16.00\" fill=\"#000000\">4</text>\n</g>\n<!-- node_1606797108896&#45;&gt;node_1606797087591 -->\n<g id=\"edge3\" class=\"edge\">\n<title>node_1606797108896&#45;&gt;node_1606797087591</title>\n<path fill=\"none\" stroke=\"#000000\" d=\"M51.0692,-66.3525C44.8017,-57.5513 36.7157,-46.1965 29.7415,-36.403\"/>\n<polygon fill=\"#404040\" stroke=\"#000000\" points=\"31.8231,-34.4989 24.9017,-29.6066 27.2615,-37.7474 31.8231,-34.4989\"/>\n</g>\n<!-- node_1606797061826 -->\n<g id=\"node_1606797061826\" class=\"node\">\n<title>node_1606797061826</title>\n<path fill=\"#ffd166\" stroke=\"#000000\" stroke-width=\".5\" d=\"M56.6667,-.5C56.6667,-.5 66.3333,-.5 66.3333,-.5 71.1667,-.5 76,-5.3333 76,-10.1667 76,-10.1667 76,-19.8333 76,-19.8333 76,-24.6667 71.1667,-29.5 66.3333,-29.5 66.3333,-29.5 56.6667,-29.5 56.6667,-29.5 51.8333,-29.5 47,-24.6667 47,-19.8333 47,-19.8333 47,-10.1667 47,-10.1667 47,-5.3333 51.8333,-.5 56.6667,-.5\"/>\n<text text-anchor=\"middle\" x=\"61.2992\" y=\"-10.2\" font-family=\"Courier,monospace\" font-size=\"16.00\" fill=\"#000000\">2</text>\n</g>\n<!-- node_1606797108896&#45;&gt;node_1606797061826 -->\n<g id=\"edge4\" class=\"edge\">\n<title>node_1606797108896&#45;&gt;node_1606797061826</title>\n<path fill=\"none\" stroke=\"#000000\" d=\"M61.5,-66.3525C61.5,-57.9786 61.5,-47.2929 61.5,-37.8398\"/>\n<polygon fill=\"#404040\" stroke=\"#000000\" points=\"64.3001,-37.6066 61.5,-29.6066 58.7001,-37.6066 64.3001,-37.6066\"/>\n</g>\n<!-- node_1606797070857hiddenchild -->\n<!-- node_1606797070857&#45;&gt;node_1606797070857hiddenchild -->\n<!-- node_1606797129607 -->\n<g id=\"node_1606797129607\" class=\"node\">\n<title>node_1606797129607</title>\n<path fill=\"#ffd166\" stroke=\"#000000\" stroke-width=\".5\" d=\"M150.6667,-.5C150.6667,-.5 160.3333,-.5 160.3333,-.5 165.1667,-.5 170,-5.3333 170,-10.1667 170,-10.1667 170,-19.8333 170,-19.8333 170,-24.6667 165.1667,-29.5 160.3333,-29.5 160.3333,-29.5 150.6667,-29.5 150.6667,-29.5 145.8333,-29.5 141,-24.6667 141,-19.8333 141,-19.8333 141,-10.1667 141,-10.1667 141,-5.3333 145.8333,-.5 150.6667,-.5\"/>\n<text text-anchor=\"middle\" x=\"155.2992\" y=\"-10.2\" font-family=\"Courier,monospace\" font-size=\"16.00\" fill=\"#000000\">6</text>\n</g>\n<!-- node_1606797070857&#45;&gt;node_1606797129607 -->\n<g id=\"edge6\" class=\"edge\">\n<title>node_1606797070857&#45;&gt;node_1606797129607</title>\n<path fill=\"none\" stroke=\"#000000\" d=\"M118.9308,-66.3525C125.1983,-57.5513 133.2843,-46.1965 140.2585,-36.403\"/>\n<polygon fill=\"#404040\" stroke=\"#000000\" points=\"142.7385,-37.7474 145.0983,-29.6066 138.1769,-34.4989 142.7385,-37.7474\"/>\n</g>\n</g>\n</svg>\n",
          "draw_effect": false,
          "root": {
               "content": "5",
               "fillcolor": "#ffd166",
               "shape": "Mrecord",
               "id": "node_1",
               "left_child": {
                    "left_child": {
                         "left_child": null,
                         "right_child": null,
                         "content": "4",
                         "fillcolor": "#ffd166",
                         "shape": "Mrecord",
                         "id": "node_1606797087591"
                    },
                    "right_child": {
                         "left_child": null,
                         "right_child": null,
                         "content": "2",
                         "fillcolor": "#ffd166",
                         "shape": "Mrecord",
                         "id": "node_1606797061826"
                    },
                    "content": "0",
                    "fillcolor": "#ffd166",
                    "shape": "Mrecord",
                    "id": "node_1606797108896"
               },
               "right_child": {
                    "left_child": null,
                    "right_child": {
                         "left_child": null,
                         "right_child": null,
                         "content": "6",
                         "fillcolor": "#ffd166",
                         "shape": "Mrecord",
                         "id": "node_1606797129607"
                    },
                    "content": "1",
                    "fillcolor": "#ffd166",
                    "shape": "Mrecord",
                    "id": "node_1606797070857"
               }
          },
          "comp_id": "ERyHgrLGUBldYrYH8OXyN"
     },
     "iteration": 0,
     "hash": 1,
     "saveVersion": 3,
     "children": [
          {
               "text": ""
          }
     ]
}
    '''
    return "<h2>I'm a simple BinaryTree Component</h2>"
