from ..componentregistry import ComponentRegistry

@ComponentRegistry.register("EducativeArray")
def EducativeArray(content, session, headers, pageObj):
    '''
    {
     "type": "EducativeArray",
     "mode": "view",
     "content": {
          "version": "3.0",
          "caption": "Array of length 4",
          "svg_string": "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?>\n<!DOCTYPE svg PUBLIC \"-//W3C//DTD SVG 1.1//EN\"\n \"http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd\">\n<!-- Generated by graphviz version 2.40.1 (20161225.0304)\n -->\n<!-- Title: %0 Pages: 1 -->\n<svg width=\"127pt\" height=\"38pt\"\n viewBox=\"0.00 0.00 127.00 38.00\" xmlns=\"http://www.w3.org/2000/svg\" xmlns:xlink=\"http://www.w3.org/1999/xlink\">\n<g id=\"graph0\" class=\"graph\" transform=\"scale(1 1) rotate(0) translate(4 34)\">\n<title>%0</title>\n<!-- node_1 -->\n<g id=\"node_1\" class=\"node\">\n<title>node_1</title>\n<polygon fill=\"#bfefff\" stroke=\"#000000\" stroke-width=\".5\" points=\"0,-.5 0,-29.5 29,-29.5 29,-.5 0,-.5\"/>\n<text text-anchor=\"middle\" x=\"14.2992\" y=\"-10.2\" font-family=\"Courier,monospace\" font-size=\"16.00\" fill=\"#000000\">0</text>\n</g>\n<!-- node_2 -->\n<g id=\"node_2\" class=\"node\">\n<title>node_2</title>\n<polygon fill=\"#bfefff\" stroke=\"#000000\" stroke-width=\".5\" points=\"30,-.5 30,-29.5 59,-29.5 59,-.5 30,-.5\"/>\n<text text-anchor=\"middle\" x=\"44.2992\" y=\"-10.2\" font-family=\"Courier,monospace\" font-size=\"16.00\" fill=\"#000000\">1</text>\n</g>\n<!-- node_3 -->\n<g id=\"node_3\" class=\"node\">\n<title>node_3</title>\n<polygon fill=\"#bfefff\" stroke=\"#000000\" stroke-width=\".5\" points=\"60,-.5 60,-29.5 89,-29.5 89,-.5 60,-.5\"/>\n<text text-anchor=\"middle\" x=\"74.2992\" y=\"-10.2\" font-family=\"Courier,monospace\" font-size=\"16.00\" fill=\"#000000\">2</text>\n</g>\n<!-- node_1517899164738 -->\n<g id=\"node_1517899164738\" class=\"node\">\n<title>node_1517899164738</title>\n<polygon fill=\"#bfefff\" stroke=\"#000000\" stroke-width=\".5\" points=\"90,-.5 90,-29.5 119,-29.5 119,-.5 90,-.5\"/>\n<text text-anchor=\"middle\" x=\"104.2992\" y=\"-10.2\" font-family=\"Courier,monospace\" font-size=\"16.00\" fill=\"#000000\">3</text>\n</g>\n</g>\n</svg>\n",
          "draw_effect": false,
          "nodes": [
               {
                    "id": "node_1",
                    "content": "0",
                    "x": "50",
                    "y": "20",
                    "fillcolor": "#bfefff",
                    "textcolor": "white",
                    "strokecolor": "#FF0000"
               },
               {
                    "id": "node_2",
                    "content": "1",
                    "x": "50",
                    "y": "20",
                    "fillcolor": "#bfefff",
                    "textcolor": "white",
                    "strokecolor": "#FF0000"
               },
               {
                    "id": "node_3",
                    "content": "2",
                    "x": "50",
                    "y": "20",
                    "fillcolor": "#bfefff",
                    "textcolor": "white",
                    "strokecolor": "#FF0000"
               },
               {
                    "id": "node_1517899164738",
                    "content": "3",
                    "x": "50",
                    "y": "20",
                    "fillcolor": "#bfefff",
                    "textcolor": "white",
                    "strokecolor": "#FF0000"
               }
          ],
          "comp_id": "f3f2c008-104f-417f-9a55-93974a80ae4e"
     },
     "hash": 1,
     "iteration": 0,
     "children": [
          {
               "text": ""
          }
     ],
     "status": "normal"
}
    '''
    return "<h2>I'm a simple EducativeArray Component</h2>"
